[tool.ruff]
select = ["E", "F", "I", "UP"]
target-version = "py311"
line-length = 127

[tool.black]
target-version =  ["py311"]
line-length = 127

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = [
    "tests"
]
pythonpath = ['.']
env_files = ['.env']
