name: Axe analysis

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: Run your tests
        run: python3 -m pytest src/tests/axe_analysis.py
      # npm install
      - name: Install npm dependency
        run: npm install axe-sarif-converter
      - name: Run sarif converter
        run: npx axe-sarif-converter --input-files src/tests/axe_results.json --output-file src/tests/axe_results.sarif
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: src/tests/axe_results.sarif
